[project]
name = "comfyui-image-feeder"
description = "A ComfyUI custom node for looping through images in a folder with a visual library UI and playback controls."
version = "0.1.4"

[project.urls]
Repository = "https://github.com/ketle-man/comfyui-image-feeder"

[tool.comfy]
PublisherId = "statsu"
DisplayName = "ComfyUI Image Feeder"
Icon = "docs/thumb.png"
